-- ZONAS
insert into zonas (nombre) values ('Zona A');
insert into zonas (nombre) values ('Zona B');
insert into zonas (nombre) values ('Zona C');

-- MESAS
insert into mesas (idzona, numero, capacidad, estado) values (1, 101, 4, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (1, 102, 8, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (1, 103, 6, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (1, 104, 2, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (1, 105, 6, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (1, 106, 6, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (1, 107, 2, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (1, 108, 2, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (1, 109, 8, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (1, 110, 2, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (2, 201, 4, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (2, 202, 4, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (2, 203, 2, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (2, 204, 4, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (2, 205, 6, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (2, 206, 2, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (2, 207, 4, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (2, 208, 2, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (2, 209, 8, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (2, 210, 8, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (3, 301, 2, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (3, 302, 2, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (3, 303, 4, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (3, 304, 8, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (3, 305, 8, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (3, 306, 6, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (3, 307, 2, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (3, 308, 6, 'LIBRE');
insert into mesas (idzona, numero, capacidad, estado) values (3, 309, 4, 'OCUPADO');
insert into mesas (idzona, numero, capacidad, estado) values (3, 310, 6, 'OCUPADO');

-- CLIENTES
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Uta Neasham', 'DNI', 43054629, '6 Maple Wood Circle', 960649649, 'uneasham0@ft.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Mirna Shovell', 'DNI', 37842652, null, null, 'mshovell1@ning.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Nicolai Mates', 'RUC', 88378300382, null, null, 'nmates2@jiathis.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Audra O''Keevan', 'RUC', 21125008990, null, null, 'aokeevan3@wordpress.org');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Anni Bouller', 'RUC', 63737433671, null, null, 'abouller4@squidoo.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Kristyn Peto', 'DNI', 66301533, null, null, 'kpeto5@fema.gov');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Abelard Heskin', 'RUC', 93729171191, '313 Summerview Park', 970984907, 'aheskin6@intel.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Bibi Anstis', 'DNI', 23925229, null, null, 'banstis7@sphinn.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Aubrey Danihel', 'DNI', 69742781, null, null, 'adanihel8@mit.edu');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Lancelot Inchan', 'RUC', 83368013301, '07 Havey Street', 987866505, 'linchan9@bbb.org');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Ethan Simper', 'DNI', 38084796, '24 Lien Hill', 969310775, 'esimpera@mashable.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Byram Bangle', 'DNI', 14197450, '414 Morning Point', 941780857, 'bbangleb@usatoday.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Duke Lecointe', 'RUC', 26610334621, '91794 Eastwood Circle', 956763130, 'dlecointec@seesaa.net');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Clayson Almeida', 'RUC', 97480817068, '17 Sachs Place', 943808142, 'calmeidad@canalblog.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Ellwood Tumielli', 'RUC', 79236261795, '3 Petterle Pass', 980046899, 'etumiellie@seattletimes.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Amy Baly', 'RUC', 78992400617, '874 Eastwood Court', 936970351, 'abalyf@w3.org');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Moises Glisane', 'DNI', 77428554, null, null, 'mglisaneg@parallels.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Tait Gatteridge', 'DNI', 63844232, '3 Gateway Lane', 968026955, 'tgatteridgeh@microsoft.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Way Fifield', 'DNI', 32799353, '7 Monica Alley', 975186752, 'wfifieldi@google.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Chiarra Grint', 'DNI', 68838455, null, null, 'cgrintj@yale.edu');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Edik Mattis', 'RUC', 72012704432, '008 Donald Lane', 933657780, 'emattisk@imdb.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Inger Labrow', 'RUC', 11613464051, null, null, 'ilabrowl@nbcnews.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Richard Norker', 'RUC', 85453484107, '608 Shopko Crossing', 964949859, 'rnorkerm@time.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Nilson Murfill', 'RUC', 12043792584, '616 Mallard Plaza', 976624814, 'nmurfilln@unc.edu');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Twila Corderoy', 'RUC', 18773167297, null, null, 'tcorderoyo@macromedia.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Philip Shyram', 'DNI', 49311131, '4020 Myrtle Pass', 966327997, 'pshyramp@joomla.org');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Morissa Durdan', 'RUC', 17745774386, '49803 Sundown Junction', 950448956, 'mdurdanq@sourceforge.net');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Rosita Kalberer', 'DNI', 20811408, null, null, 'rkalbererr@google.com.au');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Goldia Clifton', 'DNI', 38816586, null, null, 'gcliftons@hhs.gov');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Ernesta Mordan', 'RUC', 16176980966, null, null, 'emordant@theguardian.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Pen Weld', 'DNI', 67914653, '1 Eliot Way', 919075590, 'pweldu@networkadvertising.org');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Theresa Cockcroft', 'DNI', 20073527, '4 Swallow Park', 975924807, 'tcockcroftv@engadget.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Otes Pecht', 'DNI', 78768911, null, null, 'opechtw@springer.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Fallon Muller', 'DNI', 49473594, '4965 Merry Lane', 984004120, 'fmullerx@arizona.edu');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Yvor Kitto', 'RUC', 32067612466, '36 Spenser Terrace', 949641736, 'ykittoy@youku.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Mariquilla Ridge', 'RUC', 67992765952, '7758 Fuller Circle', 964799607, 'mridgez@mail.ru');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Merrile Stit', 'RUC', 69421939442, null, null, 'mstit10@bizjournals.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Dewitt Shortin', 'RUC', 96568114948, '9 Buell Way', 963620632, 'dshortin11@newyorker.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Hannie Gregorace', 'DNI', 46985471, '105 Hudson Park', 949118821, 'hgregorace12@macromedia.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Elsi Bozworth', 'RUC', 96480865386, null, null, 'ebozworth13@vinaora.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Gleda Rowler', 'DNI', 32469165, null, null, 'growler14@people.com.cn');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Jasen Morrel', 'DNI', 27525676, null, null, 'jmorrel15@jugem.jp');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Oberon Resdale', 'DNI', 43370059, '6 Elmside Road', 983503555, 'oresdale16@tuttocitta.it');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Anderson Swepstone', 'RUC', 48687472257, '95 Meadow Vale Avenue', 979515150, 'aswepstone17@lycos.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Grannie Shellcross', 'DNI', 16156491, null, null, 'gshellcross18@altervista.org');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Crista Howells', 'DNI', 16095940, '073 Macpherson Point', 976060986, 'chowells19@latimes.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Pansie Furze', 'DNI', 34949198, '6 Cottonwood Drive', 938615940, 'pfurze1a@nytimes.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Christy Babbidge', 'DNI', 67662747, '3213 Havey Drive', 940020782, 'cbabbidge1b@w3.org');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Gawen Walthall', 'RUC', 83761369860, '593 Burrows Court', 927578723, 'gwalthall1c@huffingtonpost.com');
insert into clientes (nombre, tipodocumento, documento, direccion, telefono, email) values ('Jany Gapp', 'DNI', 27864979, '14975 Weeping Birch Circle', 974286419, 'jgapp1d@tripod.com');

-- RESERVAS
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (74, 4, 'Fenofibrate', '27/10/2022', '12:19', '01/10/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (62, 32, 'Cepacol', '13/10/2022', '8:55', '19/09/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (84, 40, 'A.B.H.C. Instant Hand Sanitizer Citrus Scent', '21/10/2022', '8:34', '12/09/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (82, 35, 'ARRID EXTRA EXTRA DRY XX', '08/10/2022', '16:28', '18/09/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (82, 28, 'Zodryl AC 40', '19/10/2022', '15:27', '14/09/2022', false, true);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (68, 14, 'ENTEX LQ', '18/10/2022', '20:33', '06/09/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (68, 28, 'SOMAVERT', '13/10/2022', '15:54', '14/09/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (68, 9, 'BANANA BOAT', '30/10/2022', '19:57', '22/09/2022', false, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (90, 16, 'Escitalopram', '26/10/2022', '11:14', '28/09/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (72, 30, 'rexall allergy relief', '23/10/2022', '18:41', '02/10/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (79, 26, 'Hand Sanitizer', '14/10/2022', '21:54', '05/09/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (66, 1, 'AZITHROMYCIN', '12/10/2022', '19:32', '14/09/2022', false, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (86, 14, 'Quick Relief Creamy Diaper Rash', '22/10/2022', '10:54', '04/09/2022', false, true);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (77, 40, 'Methimazole', '24/10/2022', '17:44', '06/09/2022', false, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (83, 39, 'RUE21 Cherry Antibacterial Hand Sanitizer', '20/10/2022', '18:45', '29/09/2022', false, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (68, 2, 'Haloperidol', '27/10/2022', '21:59', '18/09/2022', false, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (75, 13, 'Kali Phosphoricum Kit Refill', '15/10/2022', '16:46', '11/09/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (63, 18, 'Diethylpropion Hydrochloride', '12/10/2022', '14:03', '01/10/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (82, 27, 'Borax', '08/10/2022', '19:15', '02/09/2022', true, false);
insert into reservas (idmesa, idcliente, nombrereserva, fechareserva, horareserva, fecharegistro, activo, eliminado) values (65, 42, 'BRUSSEL SPROUTS', '18/10/2022', '11:10', '15/09/2022', true, false);

-- FORMULARIOS
insert into formularios (nombre) values ('atencion cliente');
insert into formularios (nombre) values ('reporte ventas diarias');
insert into formularios (nombre) values ('reporte ventas por producto');
insert into formularios (nombre) values ('reporte ventas mensuales');
insert into formularios (nombre) values ('administrar menu');
insert into formularios (nombre) values ('administrar perfil');
insert into formularios (nombre) values ('administrar usuario');
insert into formularios (nombre) values ('reporte de comprobantes emitidos');
insert into formularios (nombre) values ('arqueo');
insert into formularios (nombre) values ('reporte de ordenes');
insert into formularios (nombre) values ('reporte de ordenes anulados');
insert into formularios (nombre) values ('cocina');
insert into formularios (nombre) values ('reservas');
insert into formularios (nombre) values ('cambio de mesa');

-- PERFILES
insert into perfiles (nombre) values ('ADMINISTRADOR');
insert into perfiles (nombre) values ('MOZO');
insert into perfiles (nombre) values ('CAJERO');
insert into perfiles (nombre) values ('COCINA');
insert into perfiles (nombre) values ('CLIENTE');

-- PERMISOS
insert into permisos (idperfil, idformulario) values (1,1);
insert into permisos (idperfil, idformulario) values (1,2);
insert into permisos (idperfil, idformulario) values (1,3);
insert into permisos (idperfil, idformulario) values (1,4);
insert into permisos (idperfil, idformulario) values (1,5);
insert into permisos (idperfil, idformulario) values (1,6);
insert into permisos (idperfil, idformulario) values (1,7);
insert into permisos (idperfil, idformulario) values (1,8);
insert into permisos (idperfil, idformulario) values (1,9);
insert into permisos (idperfil, idformulario) values (1,10);
insert into permisos (idperfil, idformulario) values (1,11);
insert into permisos (idperfil, idformulario) values (1,12);
insert into permisos (idperfil, idformulario) values (1,13);
insert into permisos (idperfil, idformulario) values (1,14);
insert into permisos (idperfil, idformulario) values (2,1);
insert into permisos (idperfil, idformulario) values (2,14);
insert into permisos (idperfil, idformulario) values (3,1);
insert into permisos (idperfil, idformulario) values (3,2);
insert into permisos (idperfil, idformulario) values (3,3);
insert into permisos (idperfil, idformulario) values (3,4);
insert into permisos (idperfil, idformulario) values (3,8);
insert into permisos (idperfil, idformulario) values (3,9);
insert into permisos (idperfil, idformulario) values (3,10);
insert into permisos (idperfil, idformulario) values (3,11);
insert into permisos (idperfil, idformulario) values (3,13);
insert into permisos (idperfil, idformulario) values (3,14);
insert into permisos (idperfil, idformulario) values (4,12);
insert into permisos (idperfil, idformulario) values (5,1);

-- USUARIOS
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (1, 40, 'Barth', 'Leppard', 'Klamp', 63926806, 'bklamp0@yelp.com', 'khPgDYCBw', '23/04/1996', 'http://dummyimage.com/213x100.png/ff4444/ffffff', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 44, 'Mic', 'Storrier', 'Gaul', 72163743, 'mgaul1@upenn.edu', 'g2Wdr0rr9ZiY', '04/10/2004', 'http://dummyimage.com/181x100.png/cc0000/ffffff', false, 0, 67768);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 18, 'Dag', 'Coite', 'Roubeix', 71612252, 'droubeix2@usatoday.com', 'XEdqPjf5124', '07/07/1993', 'http://dummyimage.com/227x100.png/dddddd/000000', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 2, 'Dacia', 'Mosedall', 'Barkway', 65047742, 'dbarkway3@shop-pro.jp', 'tEY6JmP', '18/08/1992', 'http://dummyimage.com/106x100.png/5fa2dd/ffffff', true, 2066, 51719);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 11, 'Gabe', 'Richmond', 'Achrameev', 72408776, 'gachrameev4@ucoz.com', 'ZHmMt8OPLSM', '21/02/2000', 'http://dummyimage.com/211x100.png/5fa2dd/ffffff', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (4, 25, 'D''arcy', 'Shobbrook', 'Wyldes', 79746560, 'dwyldes5@bloglines.com', '4JvxTM0uQUl0', '15/11/1994', 'http://dummyimage.com/155x100.png/cc0000/ffffff', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 17, 'Teddie', 'Michie', 'Traviss', 62683297, 'ttraviss6@bloglines.com', 'QryYkQG', '23/12/1990', 'http://dummyimage.com/196x100.png/dddddd/000000', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 41, 'Vaughn', 'Passion', 'Garber', 61102550, 'vgarber7@dropbox.com', 'aWZGp3Zs1mAN', '14/10/2001', 'http://dummyimage.com/101x100.png/dddddd/000000', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 33, 'Preston', 'Tredgold', 'Filipyev', 67376835, 'pfilipyev8@deviantart.com', 'ObWPVe9u0ucA', '24/12/1991', 'http://dummyimage.com/220x100.png/cc0000/ffffff', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 35, 'Nathan', 'Jackways', 'Tewnion', 70001671, 'ntewnion9@chron.com', 'p87zPL49p', '15/06/2001', 'http://dummyimage.com/112x100.png/5fa2dd/ffffff', false, 2072, 15235);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 16, 'Lyle', 'Daltry', 'Tomaszewicz', 69883760, 'ltomaszewicza@stanford.edu', 'DxklnLUKUILj', '02/06/1992', 'http://dummyimage.com/218x100.png/dddddd/000000', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 10, 'Rosalinda', 'Lamasna', 'Lording', 68300642, 'rlordingb@ehow.com', 'XSk0aSTd1eK', '01/11/1995', 'http://dummyimage.com/116x100.png/ff4444/ffffff', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (4, 46, 'Ara', 'Sparwell', 'Causley', 73451644, 'acausleyc@phpbb.com', '3z6FqfpHCN', '23/05/1992', 'http://dummyimage.com/127x100.png/dddddd/000000', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (4, 16, 'Sheilakathryn', 'Haskins', 'Shelsher', 71827185, 'sshelsherd@amazonaws.com', 'MPy0hmJ', '06/03/1998', 'http://dummyimage.com/103x100.png/cc0000/ffffff', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 35, 'Yurik', 'Hedges', 'Yelding', 66717761, 'yyeldinge@admin.ch', '9BlBEANPgYQ', '19/08/1993', 'http://dummyimage.com/242x100.png/5fa2dd/ffffff', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 1, 'Abelard', 'Preedy', 'Vasilmanov', 70358380, 'avasilmanovf@nationalgeographic.com', '3yO7TSRFO', '07/04/1994', 'http://dummyimage.com/167x100.png/dddddd/000000', true, 2147, 14878);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 36, 'Adiana', 'Dewdeny', 'Lamblin', 60107385, 'alambling@cbslocal.com', 'GMj4BwaE', '03/06/1995', 'http://dummyimage.com/152x100.png/cc0000/ffffff', false, 0, 41138);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (4, 3, 'Adrienne', 'Avery', 'Lentsch', 73142180, 'alentschh@upenn.edu', 'B8gz6G1jJt', '25/06/2001', 'http://dummyimage.com/171x100.png/cc0000/ffffff', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 25, 'Winnifred', 'Livett', 'Andriveau', 57482911, 'wandriveaui@uol.com.br', '4KR6U5NmZlc', '17/02/2001', 'http://dummyimage.com/182x100.png/5fa2dd/ffffff', false, 0, 23306);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 42, 'Harlene', 'Northey', 'Stoute', 61260149, 'hstoutej@nifty.com', '1dRmjjQkvy', '05/04/1999', 'http://dummyimage.com/180x100.png/dddddd/000000', false, 2984, 57053);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 8, 'Carolyne', 'Gonzalvo', 'Wheowall', 76586382, 'cwheowallk@mashable.com', 'gf2FiRwUOf', '14/09/1997', 'http://dummyimage.com/202x100.png/ff4444/ffffff', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 43, 'Alexandrina', 'Lauxmann', 'Freebury', 66161932, 'afreeburyl@unblog.fr', 'NH76HH0ILv', '25/06/1998', 'http://dummyimage.com/153x100.png/5fa2dd/ffffff', false, 2277, 88003);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 11, 'Belicia', 'Garwell', 'Crut', 60449581, 'bcrutm@ft.com', 'WJ1E4tHzSuS', '14/06/1996', 'http://dummyimage.com/176x100.png/ff4444/ffffff', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 24, 'Avivah', 'Tuxell', 'Quincee', 59553173, 'aquinceen@usa.gov', 'bzADKzO', '03/12/1999', 'http://dummyimage.com/143x100.png/dddddd/000000', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 31, 'Cornelia', 'Diviney', 'Scolland', 73805981, 'cscollando@wix.com', '2DzSbjYVaw', '09/02/2003', 'http://dummyimage.com/119x100.png/dddddd/000000', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 20, 'Eduard', 'Claige', 'Chesshyre', 61599694, 'echesshyrep@state.tx.us', 'L0l25TJ', '03/12/2000', 'http://dummyimage.com/147x100.png/dddddd/000000', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 28, 'Lynnett', 'Ticehurst', 'Beadnall', 71258692, 'lbeadnallq@slideshare.net', 'x2Iiw7', '02/06/1992', 'http://dummyimage.com/187x100.png/dddddd/000000', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 45, 'Leona', 'Poynser', 'Torrisi', 62538437, 'ltorrisir@dmoz.org', 'x4kUHXcSK', '26/01/2002', 'http://dummyimage.com/189x100.png/cc0000/ffffff', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 14, 'Irwinn', 'Nutbrown', 'Signore', 70181561, 'isignores@yahoo.co.jp', 'JdB4C1', '30/01/1996', 'http://dummyimage.com/148x100.png/cc0000/ffffff', false, 2170, 13222);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 17, 'Dulcie', 'Tabbernor', 'Giovannelli', 61309022, 'dgiovannellit@wix.com', 'eNqWcEj', '02/02/1998', 'http://dummyimage.com/138x100.png/cc0000/ffffff', true, 0, 45942);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 7, 'Delphine', 'Dyball', 'Bargh', 77733115, 'dbarghu@cbsnews.com', 'YYzd4deKiAF', '23/02/1995', 'http://dummyimage.com/237x100.png/dddddd/000000', true, 0, 33982);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 26, 'Marcille', 'Cartmell', 'Ethelstone', 59247895, 'methelstonev@discovery.com', '28Dp01p8', '16/07/1992', 'http://dummyimage.com/134x100.png/5fa2dd/ffffff', false, 0, 21403);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (4, 33, 'Mel', 'Jakubovsky', 'O''Clery', 62006700, 'mocleryw@imageshack.us', 'ZGEBmFfvp0', '11/02/1992', 'http://dummyimage.com/201x100.png/ff4444/ffffff', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (4, 28, 'Lesya', 'Eley', 'Neary', 56696006, 'lnearyx@toplist.cz', '8ebCA7H', '02/05/1999', 'http://dummyimage.com/250x100.png/ff4444/ffffff', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (4, 26, 'Fifi', 'Gladtbach', 'McKenny', 67251340, 'fmckennyy@cdbaby.com', 'kbAE48', '08/08/1993', 'http://dummyimage.com/250x100.png/dddddd/000000', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 17, 'Isaac', 'Cust', 'Fishby', 64910547, 'ifishbyz@oakley.com', 'WSsIL81IYJV1', '23/05/1994', 'http://dummyimage.com/211x100.png/cc0000/ffffff', true, 0, 24685);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 27, 'Megen', 'Mingard', 'Desporte', 79128618, 'mdesporte10@comsenz.com', 'eb9rOHQHi', '27/01/2002', 'http://dummyimage.com/158x100.png/cc0000/ffffff', true, 0, 33468);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 38, 'Ophelie', 'Redhole', 'Ioannidis', 66426757, 'oioannidis11@dmoz.org', 'RxcfMeR', '06/06/2001', 'http://dummyimage.com/137x100.png/ff4444/ffffff', true, 0, 23889);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 21, 'Hailee', 'Scallan', 'Daintrey', 63239340, 'hdaintrey12@about.com', 'cRKkoWivS', '04/02/1999', 'http://dummyimage.com/245x100.png/5fa2dd/ffffff', true, 0, 37391);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 35, 'Edlin', 'Kupisz', 'MacCambridge', 57132567, 'emaccambridge13@usa.gov', 'dQQ70OjfRQ', '10/11/2000', 'http://dummyimage.com/197x100.png/ff4444/ffffff', true, 2653, 30201);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (3, 27, 'Dodi', 'Yesenin', 'Aronowitz', 62677116, 'daronowitz14@mapy.cz', 'GtYLgUro', '25/01/2001', 'http://dummyimage.com/153x100.png/dddddd/000000', true, 0, 25965);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 35, 'Jefferson', 'Soitoux', 'Coalbran', 65369417, 'jcoalbran15@w3.org', 'jfY2chL', '08/08/1993', 'http://dummyimage.com/212x100.png/cc0000/ffffff', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 28, 'Tremaine', 'Naisbit', 'Bentke', 59855280, 'tbentke16@mediafire.com', 'aA6Oehqc', '25/02/2002', 'http://dummyimage.com/191x100.png/5fa2dd/ffffff', false, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 21, 'Juana', 'Fogg', 'Mc Caghan', 73411340, 'jmccaghan17@samsung.com', 'VHirwt1M', '18/07/1992', 'http://dummyimage.com/194x100.png/dddddd/000000', true, 2740, 14629);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 26, 'Emelia', 'Baudain', 'Rabley', 78600335, 'erabley18@cnet.com', 'jrfk6TNErYp', '17/06/2003', 'http://dummyimage.com/101x100.png/5fa2dd/ffffff', true, 2119, 90888);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (4, 27, 'Tonya', 'Mingame', 'Degenhardt', 70110158, 'tdegenhardt19@yellowpages.com', '8nM0M4', '11/01/2001', 'http://dummyimage.com/134x100.png/ff4444/ffffff', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 3, 'Agneta', 'Nealon', 'Sambedge', 65446918, 'asambedge1a@umich.edu', '5lhRxsF', '01/05/2003', 'http://dummyimage.com/188x100.png/dddddd/000000', false, 2696, 32737);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (2, 8, 'Wilden', 'Grist', 'Lehenmann', 78008336, 'wlehenmann1b@ucsd.edu', 'ise2zi', '11/01/1998', 'http://dummyimage.com/172x100.png/cc0000/ffffff', false, 2986, 39922);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 43, 'Kippie', 'Strangward', 'Heggs', 65070560, 'kheggs1c@si.edu', 'wj7aOVhp4', '14/06/1992', 'http://dummyimage.com/137x100.png/ff4444/ffffff', true, 0, null);
insert into usuarios (idperfil, idcliente, nombre, appaterno, apmaterno, dni, email, contrasena, fechanacimiento, nombrefoto, eliminado, numeromozo, clave) values (5, 40, 'Tripp', 'Greber', 'Langland', 73778332, 'tlangland1d@si.edu', '63eEOONjd', '02/12/1993', 'http://dummyimage.com/170x100.png/ff4444/ffffff', false, 0, null);

-- ORDENES
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (75, 44, 'PENDIENTE', null, 'T', '02/11/2022', true, 1);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (84, 40, 'PENDIENTE', 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu', 'M', '02/11/2022', true, 2);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (68, 11, 'PAGADO', null, 'M', '02/11/2022', false, 3);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (81, 45, 'CANCELADO', null, 'M', '02/11/2022', true, 4);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (75, 4, 'CANCELADO', 'massa donec dapibus duis at', 'M', '02/11/2022', true, 5);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (69, 40, 'PAGADO', null, 'T', '02/11/2022', false, 6);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (71, 9, 'CANCELADO', null, 'M', '02/11/2022', true, 7);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (71, 9, 'CANCELADO', 'congue risus semper porta volutpat quam pede lobortis ligula sit', 'M', '02/11/2022', true, 8);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (82, 11, 'PENDIENTE', 'aliquet massa id lobortis convallis tortor risus dapibus augue', 'T', '02/11/2022', false, 9);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (84, 11, 'CANCELADO', null, 'T', '02/11/2022', false, 10);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (66, 4, 'PENDIENTE', null, 'T', '02/11/2022', true, 11);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (63, 40, 'CANCELADO', 'felis fusce posuere felis sed', 'T', '02/11/2022', false, 12);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (66, 20, 'CANCELADO', null, 'M', '02/11/2022', true, 13);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (83, 9, 'CANCELADO', null, 'T', '02/11/2022', false, 14);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (88, 10, 'PAGADO', null, 'T', '02/11/2022', false, 15);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (63, 4, 'PENDIENTE', null, 'T', '02/11/2022', false, 16);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (82, 9, 'PENDIENTE', null, 'T', '02/11/2022', false, 17);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (86, 8, 'PAGADO', 'vitae ipsum aliquam non mauris morbi', 'T', '02/11/2022', false, 18);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (69, 44, 'PAGADO', null, 'T', '02/11/2022', false, 19);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (76, 48, 'PAGADO', null, 'T', '02/11/2022', true, 20);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (63, 4, 'PENDIENTE', null, 'T', '02/11/2022', true, 21);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (79, 11, 'PENDIENTE', null, 'M', '02/11/2022', true, 22);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (66, 4, 'PAGADO', null, 'M', '02/11/2022', true, 23);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (68, 20, 'CANCELADO', 'justo maecenas rhoncus aliquam lacus morbi quis', 'T', '02/11/2022', false, 24);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (62, 16, 'CANCELADO', null, 'T', '02/11/2022', true, 25);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (80, 10, 'PENDIENTE', null, 'M', '02/11/2022', true, 26);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (84, 40, 'PENDIENTE', null, 'M', '02/11/2022', false, 27);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (63, 29, 'PAGADO', null, 'T', '02/11/2022', true, 28);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (72, 4, 'PENDIENTE', null, 'T', '02/11/2022', true, 29);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (76, 5, 'PAGADO', null, 'M', '02/11/2022', true, 30);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (89, 10, 'CANCELADO', null, 'T', '02/11/2022', false, 31);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (76, 45, 'CANCELADO', null, 'T', '02/11/2022', true, 32);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (82, 47, 'PENDIENTE', null, 'T', '02/11/2022', true, 33);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (90, 16, 'PENDIENTE', null, 'M', '02/11/2022', false, 34);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (67, 40, 'PAGADO', 'neque aenean auctor gravida sem praesent id massa id', 'T', '02/11/2022', false, 35);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (80, 45, 'CANCELADO', null, 'M', '02/11/2022', true, 36);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (82, 4, 'PENDIENTE', null, 'T', '02/11/2022', false, 37);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (82, 9, 'PENDIENTE', null, 'T', '02/11/2022', true, 38);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (86, 29, 'PAGADO', null, 'M', '02/11/2022', false, 39);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (63, 29, 'PENDIENTE', null, 'T', '02/11/2022', true, 40);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (68, 5, 'PENDIENTE', null, 'T', '02/11/2022', true, 41);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (77, 5, 'CANCELADO', null, 'M', '02/11/2022', true, 42);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (83, 29, 'PAGADO', null, 'T', '02/11/2022', true, 43);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (76, 29, 'PAGADO', null, 'M', '02/11/2022', true, 44);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (74, 10, 'CANCELADO', null, 'M', '02/11/2022', false, 45);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (86, 5, 'PAGADO', null, 'T', '02/11/2022', true, 46);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (72, 20, 'PENDIENTE', null, 'T', '02/11/2022', true, 47);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (84, 16, 'PENDIENTE', null, 'M', '02/11/2022', true, 48);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (62, 47, 'CANCELADO', null, 'T', '02/11/2022', false, 49);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (87, 8, 'PAGADO', null, 'M', '02/11/2022', true, 50);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (67, 45, 'PAGADO', null, 'T', '02/11/2022', false, 51);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (61, 5, 'PAGADO', 'integer a nibh in quis', 'M', '02/11/2022', false, 52);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (64, 20, 'PENDIENTE', null, 'M', '02/11/2022', false, 53);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (85, 48, 'PENDIENTE', null, 'M', '02/11/2022', true, 54);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (70, 22, 'PENDIENTE', null, 'M', '02/11/2022', false, 55);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (62, 45, 'PENDIENTE', null, 'T', '02/11/2022', true, 56);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (84, 5, 'PENDIENTE', 'libero nullam sit amet turpis', 'M', '02/11/2022', false, 57);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (79, 45, 'PAGADO', null, 'T', '02/11/2022', true, 58);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (61, 10, 'PENDIENTE', null, 'T', '02/11/2022', true, 59);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (69, 11, 'PENDIENTE', null, 'T', '02/11/2022', false, 60);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (68, 22, 'PAGADO', 'in hac habitasse platea dictumst etiam faucibus cursus urna', 'M', '02/11/2022', true, 61);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (76, 9, 'PAGADO', null, 'M', '02/11/2022', false, 62);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (87, 22, 'PENDIENTE', null, 'M', '02/11/2022', false, 63);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (87, 48, 'PENDIENTE', null, 'M', '02/11/2022', true, 64);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (79, 29, 'PAGADO', null, 'T', '02/11/2022', true, 65);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (62, 8, 'CANCELADO', null, 'T', '02/11/2022', true, 66);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (73, 20, 'PAGADO', null, 'T', '02/11/2022', false, 67);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (71, 29, 'PAGADO', null, 'T', '02/11/2022', true, 68);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (87, 10, 'PAGADO', 'amet sapien dignissim vestibulum vestibulum ante', 'T', '02/11/2022', true, 69);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (67, 9, 'PAGADO', null, 'M', '02/11/2022', true, 70);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (80, 8, 'PENDIENTE', null, 'T', '02/11/2022', true, 71);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (88, 29, 'PENDIENTE', null, 'M', '02/11/2022', false, 72);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (86, 20, 'PENDIENTE', null, 'M', '02/11/2022', false, 73);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (65, 40, 'CANCELADO', null, 'T', '02/11/2022', true, 74);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (78, 40, 'CANCELADO', null, 'M', '02/11/2022', false, 75);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (73, 4, 'CANCELADO', null, 'M', '02/11/2022', true, 76);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (79, 16, 'PAGADO', null, 'T', '02/11/2022', false, 77);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (67, 44, 'PAGADO', null, 'T', '02/11/2022', false, 78);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (84, 11, 'PENDIENTE', null, 'T', '02/11/2022', true, 79);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (85, 22, 'PENDIENTE', null, 'M', '02/11/2022', false, 80);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (80, 16, 'PENDIENTE', null, 'T', '02/11/2022', false, 81);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (88, 44, 'CANCELADO', 'vulputate justo in blandit ultrices enim lorem', 'M', '02/11/2022', false, 82);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (77, 8, 'CANCELADO', null, 'M', '02/11/2022', false, 83);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (65, 40, 'CANCELADO', 'imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 'T', '02/11/2022', true, 84);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (62, 9, 'CANCELADO', null, 'M', '02/11/2022', true, 85);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (89, 45, 'PAGADO', 'ipsum primis in faucibus orci luctus et ultrices', 'M', '02/11/2022', false, 86);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (72, 16, 'PENDIENTE', null, 'M', '02/11/2022', false, 87);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (90, 5, 'PAGADO', null, 'T', '02/11/2022', true, 88);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (80, 10, 'PENDIENTE', null, 'T', '02/11/2022', false, 89);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (65, 29, 'CANCELADO', null, 'M', '02/11/2022', true, 90);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (79, 10, 'PAGADO', null, 'T', '02/11/2022', true, 91);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (80, 47, 'PENDIENTE', null, 'T', '02/11/2022', false, 92);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (76, 8, 'PENDIENTE', 'eget orci vehicula condimentum curabitur in', 'M', '02/11/2022', true, 93);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (70, 9, 'PAGADO', null, 'T', '02/11/2022', true, 94);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (77, 9, 'CANCELADO', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus', 'T', '02/11/2022', false, 95);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (73, 5, 'PAGADO', null, 'M', '02/11/2022', true, 96);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (79, 20, 'PENDIENTE', 'faucibus accumsan odio curabitur convallis duis', 'M', '02/11/2022', true, 97);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (75, 10, 'PAGADO', null, 'M', '02/11/2022', false, 98);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (66, 20, 'PENDIENTE', null, 'M', '02/11/2022', true, 99);
insert into ordenes (idmesa, idusuarioatencion, estado, observacion, turno, fechacreacion, atendidococina, correlativodiario) values (68, 22, 'CANCELADO', null, 'T', '02/11/2022', false, 100);

-- CAMBIOS MESA
insert into cambio_mesas (idorden, idmesaanterior, motivo) values (45,69,'la mesa esta inestable');
insert into cambio_mesas (idorden, idmesaanterior, motivo) values (15,70,'ocurrio un insidente');
insert into cambio_mesas (idorden, idmesaanterior, motivo) values (40,71,'esta expuesto al sol');

-- CATEGORIAS MENU
insert into categoria_menus (nombre, cocina) values ('Gaseosas',false);
insert into categoria_menus (nombre, cocina) values ('Cervezas', false);
insert into categoria_menus (nombre, cocina) values ('Infusiones', false);
insert into categoria_menus (nombre, cocina) values ('Aguas', false);
insert into categoria_menus (nombre, cocina) values ('sopas', true);
insert into categoria_menus (nombre, cocina) values ('Chaufa', true);
insert into categoria_menus (nombre, cocina) values ('Pollo', true);
insert into categoria_menus (nombre, cocina) values ('Pato',true);
insert into categoria_menus (nombre, cocina) values ('Res', true);
insert into categoria_menus (nombre, cocina) values ('Cerdo',true);
insert into categoria_menus (nombre, cocina) values ('Pescado',true);
insert into categoria_menus (nombre, cocina) values ('Langostino', true);
insert into categoria_menus (nombre, cocina) values ('Tortilla',true);
insert into categoria_menus (nombre, cocina) values ('Vegetarianos', true);
insert into categoria_menus (nombre, cocina) values ('Tallarines', true);
insert into categoria_menus (nombre, cocina) values ('Vinos',false);
insert into categoria_menus (nombre, cocina) values ('Refrescos',false);

-- MENUS
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Inca Cola - Personal',4.00,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Inca Cola (1/2 Litro)', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Inca Cola (1 Litro)', 9,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Inca Cola (2 Litros)', 15,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Coca Cola (Personal)', 4,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Coca Cola (1/2 Litro)', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Coca Cola (1 Litro)', 9,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Coca Cola (2 Litros)', 15,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Fanta (Personal)', 4,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Fanta (1/2 Litro)', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Sprite (Personal)', 2.5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Sprite (1/2 Litro)', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Gaseosa Cero (1/2 Litro)', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Inca Cola Zero', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (1,'Coca Cola Zero', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Cusqueña Dorada (330 Ml)', 8,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Cusqueña Dorada (620 Ml)', 10,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Cusqueña Malta (330Ml)', 8,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Cusqueña Malta (620Ml)', 10,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Cusqueña Trigo (330 Ml)', 8,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Cusqueña Trigo (620 Ml)', 10,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Cusqueña Red Lager(330 Ml)', 8,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Cusqueña Trigo (620 Ml)', 10,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Cusqueña Red Lager(330 Ml)', 8,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Corona Extra (330 Ml)', 9.5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (2,'Heineken', 10,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (3,'Te Jazmin (Tasa)', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (3,'Te Jazmin (Tetera)', 12,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (3,'Te Verde (Tasa)', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (3,'Te Verde (Tetera)', 12,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (3,'Taza Anis', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (3,'Taza Manzanilla', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (3,'Taza Hierba Luisa', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (3,'Taza Te Puro', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (3,'Taza Canela Y Clavo', 5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (4,'San Mateo Sin Gas (600 Ml)', 4,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (4,'San Luis Sin Gas', 4,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (4,'Agua San Mateo Con Gas', 4,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (4,'Agua San Luis Con Gas', 4,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (5,'Wantan Personal', 18,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (5,'Sopa Wantan Sopera', 55,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (5,'Sopa Wantan Especial Personal', 22,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (5,'Wantan Especial Sopera', 63,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (5,'Siukao Personal', 26,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (5,'Pacpow Personal', 20,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (5,'Pacpow Sopera', 60,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (5,'Samsi Personal', 18,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (5,'Samsi Sopera', 58,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (5,'Womin Personal', 18,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (6,'Chaufa Con Pollo Personal', 18,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (6,'Chaufa Con Pollo Fuente', 42,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (6,'Chaufa Con Cerdo Asado Personal', 20,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (6,'Chaufa Con Pollo Y Cerdo Personal', 21,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (6,'Chaufa Especial Fuente', 65,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (6,'Chaufa Con Pato Asado Personal', 25,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (6,'Chaufa Con Res Personal', 18,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (6,'Chaufa Vegetariano Personal', 18,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (7,'Pollo Con Almendras Chinas', 45,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (7,'Pollo Chijaukay', 45,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (7,'Pollo Tipacay', 40,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (7,'Pollo Salteado Con Verduras', 40,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (7,'Pollo Con Frejolito Chino', 40,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (7,'Pollo Funkin Choulon', 55,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (8,'Pato Kintou', 75,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (8,'Pato Cheipeikay', 75,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (8,'Pato Con Frejolito Chino', 60,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (8,'Pato Con Salsa Tausi', 60,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (8,'Pato Al Curry', 60,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (8,'Pato Picante', 60,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (8,'Pato Con Piña Y Durazno', 60,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (9,'Res Con Salsa Tausi', 48,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (9,'Res Con Salsa Ostion', 48,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (9,'Res Al Curry', 48,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (10,'Lomo De Cerdo Con Salsa Ostion', 50,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (10,'Lomo De Cerdo Con Piña Y Duraznos', 50,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (10,'Cerdo Asado Con Salsa Ostion', 50,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (10,'Cerdo Asado Al Ajo', 50,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (10,'Costillitas De Cerdo Picantes', 50,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (11,'Pescado Con Salsa Ostion', 40,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (11,'Pescado Con Salsa Tausi', 40,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (11,'Pescado Al Ajo', 40,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (11,'Pescado Al Vapor Con Tausi', 40,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (11,'Pescado En Salsa Capon', 40,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (12,'Langostinos Con Salsa Ostion', 57,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (12,'Langostino Con Salsa Tausi', 57,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (12,'Langostinos Al Ajo', 57,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (12,'Langostinos Kintou', 57,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (12,'Langostinos Con Almendras Chinas', 57,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (12,'Langostinos Picantes', 57,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (13,'Tortilla Con Pollo', 32,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (13,'Tortilla Con Cerdo Asado', 33,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (13,'Tortilla Con Pato', 35,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (13,'Tortilla Con Res', 33,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (13,'Tortillas Con Verduras', 26,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (14,'Rueda De Verduras', 65,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (14,'Verduras Salteadas', 28,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (14,'Frejolitos Salteadas', 32,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (14,'Choisan Salteado', 32,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (14,'Porcion Brocoli', 10,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (15,'Tallarines Con Taypa Especial', 65,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (15,'Tallarines Con Pollo Saltado', 42,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (15,'Tallarines Con Pollo Al Curry', 47,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (15,'Tallarines Con Pato Con Salsa Ostion', 60,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (15,'Tallarines Con Championes', 32,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (16,'Tacama Gran Blanco (Vino Peruano)', 75,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (16,'Marquez De Riscal (Vino Español)', 110,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (16,'Tabernero Gran Tinto (Vino Peruano)', 65,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (16,'Tinto De La Viña (Vino Peruano)', 80,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (17,'Limonada (Vaso)', 6,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (17,'Chicha Morada (Vaso)', 6.5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (17,'Chicha Morada (Jarra)', 16.5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (17,'Maracuya (Vaso)', 6.5,' ');
insert into menus (idcategoriamenu, nombre, precio, descripcion) values (17,'Maracuya (Jarra)', 16,' ');

-- RODUCTOS
insert into productos (nombre, descripcion) values ('arroz',' ');
insert into productos (nombre, descripcion) values ('pechuga de pollo',' ');
insert into productos (nombre, descripcion) values ('salchicha fresca',' ');
insert into productos (nombre, descripcion) values ('pimienta roja',' ');
insert into productos (nombre, descripcion) values ('huevo',' ');
insert into productos (nombre, descripcion) values ('cebolla china',' ');
insert into productos (nombre, descripcion) values ('jengibre rayado',' ');
insert into productos (nombre, descripcion) values ('aceite',' ');
insert into productos (nombre, descripcion) values ('salsa de ostion',' ');
insert into productos (nombre, descripcion) values ('salsa de soja',' ');

-- INGREDIENTES
insert into ingredientes (idmenu, idproducto, cantidad, unidades) values (51, 2,300,'g');
insert into ingredientes (idmenu, idproducto, cantidad, unidades) values (51, 3,1,'unid');
insert into ingredientes (idmenu, idproducto, cantidad, unidades) values (51, 4,1, 'unid');
insert into ingredientes (idmenu, idproducto, cantidad, unidades) values (51, 5,0.5,'unid');
insert into ingredientes (idmenu, idproducto, cantidad, unidades) values (51, 6,4,'unid');
insert into ingredientes (idmenu, idproducto, cantidad, unidades) values (51, 7,4, 'unid');
insert into ingredientes (idmenu, idproducto, cantidad, unidades) values (51, 8,1,'cdita');
insert into ingredientes (idmenu, idproducto, cantidad, unidades) values (51, 9,1,'chorro');
insert into ingredientes (idmenu, idproducto, cantidad, unidades) values (51, 10,1,'cdita');
insert into ingredientes (idmenu, idproducto, cantidad, unidades) values (51, 11,125,'ml');

-- COMBOS
insert into combos (nombre, descripcion, precio) values ('Dragon rojo',' ',59.90);

-- MENUS COMBO
insert into menu_combos (idmenu, idcombo) values (29,1);
insert into menu_combos (idmenu, idcombo) values (40,1);
insert into menu_combos (idmenu, idcombo) values (60,1);

-- MEDIOS-VENTA
insert into medios_venta (medio, abreviacion) values ('EFETIVO','E');
insert into medios_venta (medio, abreviacion) values ('TARJETA','T');

-- ARQUEOS CAJA
insert into arqueos_caja (idusuario, fecha, turno) values (1, '20/12/2021', 'T');
insert into arqueos_caja (idusuario, fecha, turno) values (2, '19/08/2022', 'T');
insert into arqueos_caja (idusuario, fecha, turno) values (3, '07/01/2022', 'T');
insert into arqueos_caja (idusuario, fecha, turno) values (4, '24/04/2022', 'M');
insert into arqueos_caja (idusuario, fecha, turno) values (5, '21/04/2022', 'M');
insert into arqueos_caja (idusuario, fecha, turno) values (6, '14/12/2021', 'M');
insert into arqueos_caja (idusuario, fecha, turno) values (7, '12/11/2021', 'T');
insert into arqueos_caja (idusuario, fecha, turno) values (8, '23/03/2022', 'M');
insert into arqueos_caja (idusuario, fecha, turno) values (9, '16/07/2022', 'M');
insert into arqueos_caja (idusuario, fecha, turno) values (10, '28/09/2022', 'M');

-- MEDIOS ARQUEO
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (8, 'TARJETA', 'T', 0, 892, 'CAJA CUADRADA', 0);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (3, 'EFECTIVO', 'E', 90, 775, 'FALTANTE DINERO', 18);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (7, 'TARJETA', 'T', 0, 530, 'FALTANTE DINERO', 18);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (9, 'EFECTIVO', 'E', 70, 698, 'SOBRANTE DINERO', 17);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (3, 'TARJETA', 'T', 0, 879, 'FALTANTE DINERO', 11);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (10, 'EFECTIVO', 'E', 99, 518, 'CAJA CUADRADA', 0);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (5, 'EFECTIVO', 'E', 87, 956, 'CAJA CUADRADA', 0);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (1, 'TARJETA', 'T', 0, 807, 'FALTANTE DINERO', 11);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (3, 'EFECTIVO', 'E', 97, 650, 'SOBRANTE DINERO', 14);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (3, 'TARJETA', 'T', 0, 549, 'FALTANTE DINERO', 17);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (1, 'TARJETA', 'T', 0, 641, 'CAJA CUADRADA', 0);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (2, 'EFECTIVO', 'E', 59, 645, 'CAJA CUADRADA', 0);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (3, 'EFECTIVO', 'E', 54, 995, 'FALTANTE DINERO', 17);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (4, 'EFECTIVO', 'E', 87, 828, 'CAJA CUADRADA', 0);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (5, 'EFECTIVO', 'E', 54, 597, 'CAJA CUADRADA', 0);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (6, 'TARJETA', 'T', 0, 956, 'FALTANTE DINERO', 19);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (7, 'EFECTIVO', 'E', 68, 958, 'FALTANTE DINERO', 15);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (8, 'EFECTIVO', 'E', 95, 596, 'SOBRANTE DINERO', 10);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (9, 'EFECTIVO', 'E', 81, 598, 'FALTANTE DINERO', 12);
insert into medios_arqueo (idarqueocaja, medio, abreviacion, saldoinicial, totalingresos, descuadre, montodescuadre) values (10, 'TARJETA', 'T', 0, 844, 'CAJA CUADRADA', 0);

-- VENTAS
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (2, 24, 10, '06/09/2022', false, 100, 'T');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (2, 40, 3, '06/10/2022', false, 21, 'M');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (2, 33, 4, '23/08/2022', true, 51, 'T');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (2, 8, 4, '27/09/2022', true, 52, 'M');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (1, 13, 6, '09/10/2022', false, 82, 'T');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (1, 10, 5, '07/09/2022', true, 53, 'M');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (2, 11, 2, '20/09/2022', false, 103, 'M');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (2, 38, 9, '15/09/2022', true, 74, 'T');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (2, 43, 9, '30/08/2022', false, 74, 'M');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (2, 33, 9, '22/08/2022', true, 25, 'T');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (2, 18, 9, '27/08/2022', true, 105, 'M');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (1, 31, 3, '10/08/2022', false, 76, 'T');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (1, 8, 2, '14/08/2022', false, 56, 'M');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (1, 39, 3, '03/10/2022', true, 77, 'M');
insert into ventas (idmedioventa, idcliente, idarqueocaja, fecha, ventadirecta, total, turno) values (1, 6, 2, '29/09/2022', true, 57, 'M');

-- COMPROBANTES

insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (1, 1001, 'NOTA VENTA', 'NV', null, 58277958);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (2, 1002, 'FACTURA', 'F', 'Flashspan', 98029541158);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (3, 1003, 'BOLETA', 'B', 'Youspan', 78027774536);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (4, 1004, 'BOLETA', 'B', 'Latz', 54331209097);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (5, 1005, 'FACTURA', 'F', 'Fadeo', 72034809238);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (6, 1006, 'NOTA VENTA', 'NV', null, 47610371);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (7, 1007, 'FACTURA', 'F', 'Realpoint', 52115851568);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (8, 1008, 'NOTA VENTA', 'NV', null, 68329159);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (9, 1009, 'BOLETA', 'B', 'Mycat', 18550512910);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (10, 1010, 'BOLETA', 'B', 'Flashpoint', 59037570887);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (11, 1011, 'NOTA VENTA', 'NV', null, 67947659);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (12, 1012, 'BOLETA', 'B', 'Shufflebeat', 49410409298);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (13, 1013, 'BOLETA', 'B', 'Jaxbean', 46685330393);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (14, 1014, 'NOTA VENTA', 'NV', null, 72104400);
insert into comprobantes (idventa, numero, nombre, abreviacion, razonsocial, rucdni) values (15, 1015, 'BOLETA', 'B', 'Skyndu', 29790649474);

-- DETALLE ORDENES
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (62, 6, 109, null, 'Limonada (Vaso)', 2, 10, 20, false, 'PAGADO', 1, null, false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (40, 14, 80, null, 'Pescado Con Salsa Tausi', 2, 10, 20, false, 'PAGADO', 2, null, false, false, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (86, 5, null, 1, 'Dragon rojo', 4, 10, 40, true, 'CANCELADO', 3, null, false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (30, 9, null, 1, 'Dragon rojo', 2, 10, 20, true, 'CANCELADO', 4, 'felis eu sapien cursus vestibulum proin eu mi', false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (65, 9, 66, null, 'Pato Con Frejolito Chino', 3, 10, 30, false, 'CANCELADO', 5, null, true, true, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (45, 2, 58, null, 'Pollo Con Almendras Chinas', 2, 10, 20, false, 'CANCELADO', 6, null, true, true, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (41, 10, 4, null, 'Inca Cola (2 Litros)', 2, 10, 20, false, 'PAGADO', 7, 'platea dictumst etiam faucibus cursus urna ut tellus nulla', false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (33, 2, 66, null, 'Pato Con Frejolito Chino', 1, 10, 10, false, 'PAGADO', 8, null, true, true, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (77, 12, 83, null, 'Pescado En Salsa Capon', 2, 10, 20, false, 'PAGADO', 9, 'luctus et ultrices posuere cubilia curae duis', true, true, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (19, 13, 107, null, 'Tabernero Gran Tinto (Vino Peruano)', 4, 10, 40, false, 'PENDIENTE', 10, null, false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (76, 2, 91, null, 'Tortilla Con Cerdo Asado', 3, 10, 30, false, 'PENDIENTE', 11, 'lorem quisque ut erat curabitur gravida nisi at nibh in', true, true, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (97, 10, 63, null, 'Pollo Funkin Choulon', 3, 10, 30, false, 'CANCELADO', 12, null, false, false, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (89, 14, 49, null, 'Womin Personal', 4, 10, 40, false, 'PENDIENTE', 13, null, true, true, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (23, 4, 68, null, 'Pato Al Curry', 1, 10, 10, false, 'PAGADO', 14, null, true, true, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (57, 5, 1, null, 'Inca Cola - Personal', 3, 10, 30, false, 'PENDIENTE', 15, 'vestibulum quam sapien varius ut blandit non', false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (2, 11, 13, null, 'Gaseosa Cero (1/2 Litro)', 1, 10, 10, false, 'PAGADO', 16, null, false, false, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (6, 11, 57, null, 'Chaufa Vegetariano Personal', 1, 10, 10, false, 'PENDIENTE', 17, 'eget nunc donec quis orci eget orci', false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (54, 5, 40, null, 'Wantan Personal', 3, 10, 30, false, 'PAGADO', 18, null, true, true, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (29, 10, 31, null, 'Taza Anis', 3, 10, 30, false, 'PENDIENTE', 19, null, false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (96, 5, null, 1, 'Dragon rojo', 1, 10, 10, true, 'CANCELADO', 20, null, true, true, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (44, 9, 3, null, 'Inca Cola (1 Litro)', 3, 10, 30, false, 'PENDIENTE', 21, null, false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (54, 8, 56, null, 'Chaufa Con Res Personal', 2, 10, 20, false, 'PENDIENTE', 22, 'nunc rhoncus dui vel', false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (10, 13, null, 1, 'Dragon rojo', 1, 10, 10, true, 'CANCELADO', 23, null, false, false, false);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (57, 6, 6, null, 'Coca Cola (1/2 Litro)', 1, 10, 10, false, 'CANCELADO', 24, null, true, true, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (61, 13, 19, null, 'Cusqueña Malta (620Ml)', 4, 10, 40, false, 'PENDIENTE', 25, null, false, false, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (73, 8, 95, null, 'Rueda De Verduras', 1, 10, 10, false, 'PENDIENTE', 26, 'diam neque vestibulum', false, false, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (60, 13, 39, null, 'Agua San Luis Con Gas', 3, 10, 30, false, 'CANCELADO', 27, 'in faucibus orci luctus et ultrices posuere cubilia curae', false, false, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (75, 5, 41, null, 'Sopa Wantan Sopera', 3, 10, 30, false, 'PAGADO', 28, null, true, true, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (93, 14, 33, null, 'Taza Hierba Luisa', 3, 10, 30, false, 'PAGADO', 29, 'mi integer ac neque duis bibendum morbi non quam', true, true, true);
insert into detalle_ordenes (idorden, idventa, idmenu, idcombo, nombremenu, cantidad, preciounitario, preciototal, escombo, estado, observacion, notacocina, llevar, delivery, atendidococina) values (65, 9, 1, null, 'Inca Cola - Personal', 2, 10, 20, false, 'CANCELADO', 30, null, false, false, false);





